name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y libffi-dev libssl-dev liblzma-dev zlib1g-dev libncurses5
        pip install --upgrade pip
        pip install buildozer cython

    - name: Build APK
      run: |
        sudo apt install -y openjdk-11-jdk
        buildozer -v android debug

    - name: Upload APK to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: built-apk
        path: bin/*.apk 
