name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggers

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip libffi-dev libssl-dev git
        pip install buildozer

    - name: Setup Android SDK
      run: |
        sudo apt install -y openjdk-11-jdk
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

    - name: Install Buildozer Android dependencies
      run: |
        sudo apt install -y zlib1g-dev libc6-dev
        buildozer android sdk

    - name: Build APK
      run: |
        buildozer init  # Only if buildozer.spec doesn't exist
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: bin/*.apk
